[alias]
coverage_0 = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage", "--features", ""]
coverage_1 = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage", "--features", "unsafe_debug"]
coverage_open = 'llvm-cov --no-run --open --output-dir ./target/coverage'
